version: '3.3'
services:
  db:
    build: ./db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'foko'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'mysql'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3333:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted